import pygame

# Screen dimensions
WIDTH = 1000
HEIGHT = 700
FPS = 60

# Game balance constants
PLAYER_BASE_SPEED = 4
PLAYER_BASE_HEALTH = 130
PLAYER_DASH_SPEED = 12
PLAYER_DASH_DURATION = 8
PLAYER_DASH_COOLDOWN = 60
PLAYER_SHOOT_COOLDOWN = 8
PLAYER_PROJECTILE_DAMAGE = 4
PLAYER_PROJECTILE_SPEED = 10

# Combat constants
DAMAGE_INVINCIBILITY_FRAMES = 60
HIT_FLASH_DURATION = 10
SCREEN_SHAKE_DURATION = 12
SCREEN_SHAKE_LIGHT = 8
PROJECTILE_DEFAULT_LIFETIME = FPS * 10
PROJECTILE_OFFSCREEN_BUFFER = 50

# Boss constants
BOSS_INTRO_DURATION = 120
BOSS_WEAKENED_HEALTH_MULTIPLIER = 0.65
BOSS_GLOBAL_HEALTH_MULTIPLIER = 0.70
BOSS_PHASE_2_THRESHOLD = 0.6
BOSS_PHASE_3_THRESHOLD = 0.3

# Upgrade constants
UPGRADE_COUNT = 4
UPGRADE_CARD_WIDTH = 220
UPGRADE_CARD_HEIGHT = 260
UPGRADE_CARD_GAP = 22
HEAL_AFTER_BOSS_PERCENTAGE = 0.30

# UI constants
HEALTH_BAR_WIDTH = 250
HEALTH_BAR_HEIGHT = 6
HEALTH_BAR_SPACING = 40
PLAYER_HEALTH_BAR_WIDTH = 40
PLAYER_HEALTH_BAR_HEIGHT = 4

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
BLUE = (0, 100, 255)
GREEN = (0, 255, 0)
YELLOW = (255, 255, 0)
PURPLE = (128, 0, 128)
ORANGE = (255, 165, 0)
CYAN = (0, 255, 255)

def init_pygame():
    """Initialize pygame - call this once at game start"""
    pygame.init()
